version: '3.8'

volumes:
  datafiles:

services:
  website:
    container_name: ottonova-php74
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
      - 8083:443
    restart: unless-stopped